// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3MOuYanGc2OZlcrRz2S5fXpL1DLXIdC0',
    appId: '1:485795396235:web:242f5177929e1912e7f28e',
    messagingSenderId: '485795396235',
    projectId: 'insta-fe761',
    authDomain: 'insta-fe761.firebaseapp.com',
    storageBucket: 'insta-fe761.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-lJk2Mcz4OWtoz9wLkwWaM2M15ea7jGQ',
    appId: '1:485795396235:android:085c2c25400fb105e7f28e',
    messagingSenderId: '485795396235',
    projectId: 'insta-fe761',
    storageBucket: 'insta-fe761.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKD8wZQiiuI9lsW7Dy9gS0GRDOU9U0EgM',
    appId: '1:485795396235:ios:b3ef0af754d30b6be7f28e',
    messagingSenderId: '485795396235',
    projectId: 'insta-fe761',
    storageBucket: 'insta-fe761.appspot.com',
    iosClientId: '485795396235-tf4r6r3g62ueefq87segeubu4rfsntt3.apps.googleusercontent.com',
    iosBundleId: 'com.example.insta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKD8wZQiiuI9lsW7Dy9gS0GRDOU9U0EgM',
    appId: '1:485795396235:ios:b3ef0af754d30b6be7f28e',
    messagingSenderId: '485795396235',
    projectId: 'insta-fe761',
    storageBucket: 'insta-fe761.appspot.com',
    iosClientId: '485795396235-tf4r6r3g62ueefq87segeubu4rfsntt3.apps.googleusercontent.com',
    iosBundleId: 'com.example.insta',
  );
}
